export const backgroundColors = {
  rock: "bg-type-rock",
  ghost: "bg-type-ghost",
  steel: "bg-type-steel",
  water: "bg-type-water",
  grass: "bg-type-grass",
  psychic: "bg-type-psychic",
  ice: "bg-type-ice",
  dark: "bg-type-dark",
  fairy: "bg-type-fairy",
  normal: "bg-type-normal",
  fighting: "bg-type-fighting",
  flying: "bg-type-flying",
  poison: "bg-type-poison",
  ground: "bg-type-ground",
  bug: "bg-type-bug",
  fire: "bg-type-fire",
  electric: "bg-type-electric",
  dragon: "bg-type-dragon",
};

export const borderColors = {
    rock: "border-type-rock",
    ghost: "border-type-ghost",
    steel: "border-type-steel",
    water: "border-type-water",
    grass: "border-type-grass",
    psychic: "border-type-psychic",
    ice: "border-type-ice",
    dark: "border-type-dark",
    fairy: "border-type-fairy",
    normal: "border-type-normal",
    fighting: "border-type-fighting",
    flying: "border-type-flying",
    poison: "border-type-poison",
    ground: "border-type-ground",
    bug: "border-type-bug",
    fire: "border-type-fire",
    electric: "border-type-electric",
    dragon: "border-type-dragon",
}

export const textColors = {
  rock: "text-type-rock",
  ghost: "text-type-ghost",
  steel: "text-type-steel",
  water: "text-type-water",
  grass: "text-type-grass",
  psychic: "text-type-psychic",
  ice: "text-type-ice",
  dark: "text-type-dark",
  fairy: "text-type-fairy",
  normal: "text-type-normal",
  fighting: "text-type-fighting",
  flying: "text-type-flying",
  poison: "text-type-poison",
  ground: "text-type-ground",
  bug: "text-type-bug",
  fire: "text-type-fire",
  electric: "text-type-electric",
  dragon: "text-type-dragon",
}